### ISSUE TITLE
Improvements for <sharpen-dashboard-card/>

### ISSUE THREAD

**Issue by deepakmahakale** [coggen/kezuri#18]
1. Button support: Some of our primary actions involve using the `post` method.
2. Images: 
   - Bookmark - app/assets/images/icons/bookmark.png
   - Genetic - app/assets/images/icons/dna.png
3. Instead of a fixed image can we make the hero section dynamic

**Comment by jabbett** [comment]
Examples from [CORE-2535](https://cognitivegenetics.atlassian.net/browse/CORE-2535):

![image](https://github.com/coggen/kezuri/assets/923971/61318b10-788e-4c10-a127-41568060f3a2)

![image](https://github.com/coggen/kezuri/assets/923971/b8d825bf-153d-43bb-b33a-269fa0d34920)

**Comment by jabbett** [comment]
* I've created a slot for the primary button - you can either use the `primary-link` & `primary-link-text` attributes or you can pass in a block to the `primary-button` slot. I'm updating the sharpen-dashboard-card stories to document this.
* I made a mistake in how images were loaded into the card. Previously, the image had to be a Kezuri asset, but that's obviously too limiting. You can now pass in any fully qualified image URL and it'll load appropriately.
* I would rather not make the image area dynamic. Currently, the dashboard looks messy because of how much variation there can be in the card contents. I've prepared an alternative design for showing the EAA risk level card below, and included it as a story in the documentation.

![image](https://github.com/coggen/kezuri/assets/923971/56874405-38e1-4f38-b52f-aa8e27b98dcd)

I'll post a link to the docs once I publish a new version.

**Comment by jabbett** [comment]
https://coggen.github.io/kezuri/?path=/docs/organisms-dashboard-card--docs#cards-in-a-grid
