### ISSUE TITLE
Commands mentioned in Readme doesn't work.

### ISSUE THREAD

**Issue by mohd-anas-ansari** [coggen/kezuri#26]
Issues faced:
- `bin/dev` is not present.
- `bin/storybook` is not present.

If we have changed the commands, we need to update README.

**Comment by jabbett** [comment]
Good catch! I will update in the next release.

These are the right commands:

* `npm run start`
* `npm run storybook`

Because of a Stencil bug, we previously needed a separate CSS watcher process, which was launched with those `bin` scripts. Once the bug was fixed, I removed the scripts but forgot to update the README.

**Comment by jabbett** [comment]
README updated!
